INSERT INTO SEGSISTEMA (ICVESISTEMA,ICVEUSUARIO,CNOMBRE,CDSCSISTEMA,LBLOQUEADO) VALUES (1,1,'Mi Mappir','Administrador de social add-on de mappir',0);
INSERT INTO SEGUSUARIO (ICVEUSUARIO,DTREGISTRO,CUSUARIO,CPASSWORD,CNOMBRE,CAPPATERNO,CAPMATERNO,CCALLE,CCOLONIA,ICVEPAIS,ICVEENTIDADFED,ICVEMUNICIPIO,ICODIGOPOSTAL,CTELEFONO,ICVEUNIDADORG,LBLOQUEADO,DTCAMBIOCONTRA) VALUES (1,{d '2007-02-26'},'admin','adminadmin','ADMINISTRADOR','GENERAL','DEL SISTEMA','NA','NA',1,1,1,1,'1',1,0,null);
INSERT INTO SEGGRUPO (ICVESISTEMA,ICVEGRUPO,CDSCGRUPO,LBLOQUEADO) VALUES (1,1,'ADMINISTRADORES MIMAPPIR',0);
INSERT INTO SEGGPOXUSR (ICVESISTEMA,ICVEUSUARIO,ICVEGRUPO) VALUES (1,1,1);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9999,1,1);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,1,'./inicio.jsp','Inicio',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9999,'../auth/admseglogout.action','Salir',1,1,1);
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (1,1,'Página de Inicio','#',0,0,'./inicio.jsp','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9999,1,'Salir del sistema','#',0,0,'../auth/admseglogout.action','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9800,1,'SEGURIDAD','#',0,0,'SEGURIDAD','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9810,1,'Seguridad de grupo por usuario','SEGGPOXUSR.jsp',9800,0,'./SEGGPOXUSR.jsp','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9820,1,'Seguridad de grupo','SEGGRUPO.jsp',9800,0,'./SEGGRUPO.jsp','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9830,1,'Seguridad de menu','SEGMENU.jsp',9800,0,'./SEGMENU.jsp','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9840,1,'Seguridad de permiso por grupo','SEGPERMISOXGPO.jsp',9800,0,'./SEGPERMISOXGPO.jsp','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9850,1,'Seguridad del programa','SEGPROGRAMA.jsp',9800,0,'./SEGPROGRAMA.jsp','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9860,1,'Seguridad del sistema','SEGSISTEMA.jsp',9800,0,'./SEGSISTEMA.jsp','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (9870,1,'Seguridad del usuario','SEGUSUARIO.jsp',9800,0,'./SEGUSUARIO.jsp','','');
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9800,'SEGURIDAD','Carpeta de Seguridad',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9810,'./SEGGPOXUSR.jsp','Seguridad de grupo por usuario',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9820,'./SEGGRUPO.jsp','Seguridad de grupo',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9830,'./SEGMENU.jsp','Seguridad de menu',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9840,'./SEGPERMISOXGPO.jsp','Seguridad de permiso por grupo',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9850,'./SEGPROGRAMA.jsp','Seguridad del programa',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9860,'./SEGSISTEMA.jsp','Seguridad del sistema',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,9870,'./SEGUSUARIO.jsp','Seguridad del usuario',1,1,1);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9800,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9810,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9820,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9830,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9840,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9850,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9860,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,9870,0,0);


INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (2000,1,'REVISION','#',0,0,'REVISIONES','','');
INSERT INTO SEGMENU (IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA,CCLASECSS,CICONCLS) VALUES (2110,1,'Registro de señales','QOSCSENALGEO.jsp',2000,0,'./QOSCSENALGEO.jsp','','');
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,2000,'OPERACIONES','Carpeta de Operaciones dentro del sistema',1,1,1);
INSERT INTO SEGPROGRAMA (ICVESISTEMA,ICVEPROGRAMA,CNOMBRE,CDSCPROGRAMA,LTIENEESCRITURA,LCONFIGURABLE,LBLOQUEADO) VALUES (1,2110,'./QOSCSENALGEO.jsp','Seguridad de grupo por usuario',1,1,1);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,2000,0,0);
INSERT INTO SEGPERMISOXGPO (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA,LEJECUCION,LACTUALIZACION) VALUES (1,1,2110,0,0);





DELETE from seggpoxusr;
DELETE from seggrupo;
DELETE from segpermisoxgpo;
DELETE from segmenu;
DELETE from segprograma;
DELETE from segsistema;
DELETE from segusuario;

